tasks/urls.py
from django.urls import path

from tasks.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TagCreateView,
    toggle_complete_or_undo,
    TagUpdateView,
    TagDeleteView,
    TaskUpdateView,
    TaskDeleteView)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/create", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path(
        "tasks/<int:pk>/toggle-complete/",
        toggle_complete_or_undo,
        name="toggle-complete-undo",
    ),
]

app_name = "tasks"

todo_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_datetime = models.DateTimeField(auto_now_add=True)
    deadline_datetime = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return self.content

tasks/forms.py
from django import forms

from tasks.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    deadline_datetime = forms.DateTimeField(
        widget=forms.TextInput(attrs={"placeholder": "YYYY-MM-DD HH:MM:SS"}),
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

tasks/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from tasks.forms import TaskForm
from tasks.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TagListView(generic.ListView):
    model = Tag


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:task-list")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")


class TagUpdateView(generic.UpdateView):
    models = Tag
    fields = "__all__"
    queryset = Tag.objects.all()
    success_url = reverse_lazy("tasks:tag-list")


def toggle_complete_or_undo(request, pk):
    task = Task.objects.get(id=pk)
    task.is_done = not task.is_done
    task.save()
    return redirect(reverse("tasks:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=3">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div>
    <div class="row">
      <div class="col-sm-2">

        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}

      </div>
      <div class="col-sm-10">

        {% block content %}{% endblock %}

        {% block pagination %}
          {% include "includes/pagination.html" %}
        {% endblock %}

      </div>
    </div>
  </div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul>
  <li class="list-group-item"><a href="{% url 'tasks:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:tag-list' %}">Tags</a></li>
</ul>

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'tasks:tag-list' %}">No</a>
  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a href="{% url 'tasks:tag-create' %}" class="btn btn-primary float-right mr-5">
      Add tag
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Tag</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a href="{% url "tasks:tag-update" pk=tag.id %}" class="btn btn-secondary">Update</a></td>
          <td><a href="{% url "tasks:task-delete" pk=tag.id %}" class="btn btn-danger">Delete</a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no tags!</p>
  {% endif %}
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'tasks:task-list' %}">No</a>
  </form>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/task_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'tasks:task-create' %}" class="btn btn-primary float-right mr-5">
      Add task
    </a>
  </h1>
  {% if task_list %}
    {% for task in task_list %}
      <p>
        <strong>{{ task.content }} {% if task.is_done %}<ins class="color-green">Done</ins>{% else %}<ins class="color-red">Not done</ins> {% endif %}</strong>
         {% if task.is_done %}<a href="{% url 'tasks:toggle-complete-undo' pk=task.pk %}" class="btn btn-secondary float-right mr-5">Undo</a>{% endif %}
         {% if not task.is_done %}<a href="{% url 'tasks:toggle-complete-undo' pk=task.pk %}" class="btn btn-success float-right mr-5">Complete</a>{% endif %}
      </p>
      <p>Created: {{ task.created_datetime }} {% if task.deadline_datetime %}Deadline: {{ task.deadline_datetime }}{% endif %}</p>
      <p>Tags: {% for tag  in task.tags.all %} {{ tag }} {% endfor %}
        <a class="btn btn-secondary" href="{% url "tasks:task-update" pk=task.id %}">Update</a>
        <a class="btn btn-danger" href="{% url "tasks:task-delete" pk=task.id %}">Delete</a>
      </p>
      <br>
    {% endfor %}
  {% else %}
    <p>There are no tasks to do!</p>
  {% endif %}
{% endblock %}